# Generated by Django 4.1.7 on 2023-02-16 08:03

from django.db import migrations, models
import main.models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveIntegerField(default=771691, unique=True, verbose_name='Артикль')),
                ('photo', models.ImageField(upload_to=main.models.upload_dir, verbose_name='Изображение')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('posted_by', models.CharField(max_length=100, verbose_name='Добавлено пользователем')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Нравится')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
