# Generated by Django 4.1.5 on 2023-02-19 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0009_ipmodel_remove_post_views_post_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipmodel',
            options={'verbose_name': 'ip', 'verbose_name_plural': 'ip'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AlterField(
            model_name='post',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='posted_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Добавлено пользователем'),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Нравится'),
        ),
    ]
